name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  tests:
    name: Ember tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - run: npm run test
